export const GET_PHONES_START = 'GET_PHONES_START';
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS';
export const GET_PHONES_FAILURE = 'GET_PHONES_FAILURE';
export const SELECT_PHONE_BY_ID = 'SELECT_PHONE_BY_ID';
export const SWITCH_MODAL = 'SWITCH_MODAL';
